# Generated by Django 2.2.11 on 2020-03-17 01:52

from django.db import migrations, models
import updates.models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=updates.models.upload_update_image),
        ),
    ]
